--  Body file for function Mass_Memory
--  Generated by TASTE on 2020-09-15 15:23:55
--  You can edit this file, it will not be overwritten
--  Provided interfaces : Picture
--  Required interfaces : Ack
--  Timers              : 


package body Mass_Memory is

   procedure Picture (pic : in out asn1SccPicture) is
   
      begin
         Ack;
      end Picture;


   begin
      --  Write your startup code here
      null;

end Mass_Memory;

