OPENGEODE?=opengeode

all: compile-linux

clean:
	rm -rf obj

edit:
	cd src && $(OPENGEODE) @_LOWER:Name_@.pr

generate-code:
	mkdir -p code && cd code && \
	   cp ../../../dataview/dataview-uniq.asn ../src && \
	   $(OPENGEODE) --taste --simu --toAda ../src/@_LOWER:Name_@.pr && \
	   mv *.gpr ..

compile-linux: generate-code
	CODE_PATH=code ADA_INCLUDE_PATH=../../../dataview/Ada gprbuild -p -P @_LOWER:Name_@_ada.gpr
