// Body file for function Function1
// Generated by TASTE on 2021-04-26 12:27:34
// You can edit this file, it will not be overwritten
// Provided interfaces : pulse
// Required interfaces : 
// User-defined properties for this function:
//   |_ Taste::Active_Interfaces = any
//   |_ Taste::coordinates = 157569 40286 188960 64876
// Timers              : 

#include "function1.h"
#include "function1_state.h"
#include <iostream>

// Define and use function state inside this context structure
// avoid defining global/static variable elsewhere
function1_state ctxt_function1;


void function1_startup(void)
{
   // Write your initialisation code, but DO NOT CALL REQUIRED INTERFACES
   std::cout << "[Function1] Startup" << std::endl;
}

void function1_PI_pulse(void)
{
   // Write your code here
}


