/* C++ Body file for function type CppType
 * Generated by TASTE on 2021-03-26 17:03:44
 * You can edit this file, it will not be overwritten
 * Provided interfaces : Pulse
 * Required interfaces : 
 * User-defined properties for this function:
 *   |_ Taste::Active_Interfaces = any
 *   |_ Taste::coordinates = 949 62 1451 446
 *   |_ Taste::is_Component_Type = true
 * Timers              : 
 */

#include <cstdio>
#include "cpptype.h"

// Include Context Parameters (constants defined in the Interface View)
#include "Context-cpptype.h"

void cpptype::startup()
{
   printf("C++ : %d\n", config.foo);
}

void cpptype::Pulse(void)
{
   
}

void cpptype::worker( const asn1SccT_INTEGER *a)
{
    printf("SDL (%d) asked me to work\n", *a);
}
