/* Body file for function Function2
 * Generated by TASTE on 2021-09-06 14:46:17
 * You can edit this file, it will not be overwritten
 * Provided interfaces : check
 * Required interfaces : op
 * User-defined properties for this function:
 *   |_ Taste::Active_Interfaces = any
 *   |_ Taste::coordinates = 205349 77951 274481 152752
 * Timers              :
 */

#include "function2.h"

void function2_startup(void)
{
}

void function2_PI_check
      (const asn1SccT_Int32 *IN_a)
{
   function2_RI_op(IN_a);
}
