/* Body file for function HELLO_WORLD
 * Generated by TASTE on 2020-12-21 13:46:07
 * You can edit this file, it will not be overwritten
 * Provided interfaces : hello_world
 * Required interfaces : 
 * User-defined properties for this function:
 *   |_ Taste::Active_Interfaces = any
 *   |_ Taste::coordinates = 95125 73986 150878 120755
 * Timers              : 
 */

#include "hello_world.h"
#include <stdio.h>


void hello_world_startup(void)
{
   // Write your initialisation code, but DO NOT CALL REQUIRED INTERFACES
   puts ("[HELLO_WORLD] Startup");
}

void hello_world_PI_hello_world(void)
{
   puts ("[HELLO_WORLD] Cyclic message: Hello World!\n"); 
}


